"""Creator simulation.

The point of this module is to give the engine something real to be wrong
about. A simulated creator carries a **latent preference profile** that the
recommendation engine never sees — and that deliberately disagrees with what
the creator said at signup, the way real people's stated and revealed
preferences disagree.

The simulation then:

1.  asks the engine for a Top-K slate,
2.  decides what the creator *actually* does with each item using the latent
    profile (promote / save / skip),
3.  derives the rejection reason from whichever latent term was most violated,
4.  writes those actions back through the normal feedback path.

Because the reason is generated by the real cause, the learning loop has a
genuine signal to recover rather than noise. `evaluation.py` then measures
whether it does: ranking quality is scored against the latent utility, which is
the only true ground truth that exists here.

Nothing in this module is imported by the ranking path. The engine cannot see
latent state even by accident.
"""
from __future__ import annotations

import datetime as dt
import math
import random
from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import (
    Creator,
    FeedbackEvent,
    Interaction,
    Product,
    SimulatedProfile,
    get_or_create_interaction,
)
from .pipeline import recommend

CATEGORIES = ("Skincare", "Makeup", "Haircare", "Personal Care")

# Where a creator's revealed preference tends to sit relative to what they said.
STATED_VS_REVEALED_DRIFT = 0.35


@dataclass
class LatentProfile:
    """What the simulated creator actually wants. Hidden from the engine."""

    category_affinity: dict[str, float]      # 0-1 per category
    price_ceiling: int                       # the real one, not the stated one
    price_floor: int
    trend_sensitivity: float                 # 0-1: how much momentum matters
    quality_sensitivity: float               # 0-1: how much rating matters
    commerce_sensitivity: float              # 0-1: how much conversion matters
    novelty_preference: float                # 0-1: dislike of saturated products
    promote_threshold: float = 0.62
    save_threshold: float = 0.45
    seed: int = 0
    # Products the creator has already covered; promoting twice is implausible.
    promoted: set[str] = field(default_factory=set)

    def to_json(self) -> dict:
        return {
            "category_affinity": self.category_affinity,
            "price_ceiling": self.price_ceiling,
            "price_floor": self.price_floor,
            "trend_sensitivity": round(self.trend_sensitivity, 3),
            "quality_sensitivity": round(self.quality_sensitivity, 3),
            "commerce_sensitivity": round(self.commerce_sensitivity, 3),
            "novelty_preference": round(self.novelty_preference, 3),
            "promote_threshold": self.promote_threshold,
            "save_threshold": self.save_threshold,
            "seed": self.seed,
            "promoted": sorted(self.promoted),
        }

    @classmethod
    def from_json(cls, payload: dict) -> "LatentProfile":
        return cls(
            category_affinity=payload["category_affinity"],
            price_ceiling=payload["price_ceiling"],
            price_floor=payload["price_floor"],
            trend_sensitivity=payload["trend_sensitivity"],
            quality_sensitivity=payload["quality_sensitivity"],
            commerce_sensitivity=payload["commerce_sensitivity"],
            novelty_preference=payload["novelty_preference"],
            promote_threshold=payload.get("promote_threshold", 0.62),
            save_threshold=payload.get("save_threshold", 0.45),
            seed=payload.get("seed", 0),
            promoted=set(payload.get("promoted", [])),
        )


# --------------------------------------------------------------------------
# building a latent profile
# --------------------------------------------------------------------------
def build_latent(creator: Creator, seed: int | None = None) -> LatentProfile:
    """Derive a latent profile that is *close to but not the same as* the
    stated one.

    The drift is the interesting part. A creator who signs up saying "skincare,
    Rs200-700" may in practice also take haircare, and may quietly refuse
    anything over Rs550. The engine has to find that out from behaviour.
    """
    rng = random.Random(seed if seed is not None else hash(creator.creator_id) & 0xFFFF)

    affinity: dict[str, float] = {}
    for category in CATEGORIES:
        if category == creator.niche:
            affinity[category] = round(rng.uniform(0.80, 0.98), 3)
        elif category in (creator.sub_niches or []):
            affinity[category] = round(rng.uniform(0.45, 0.75), 3)
        else:
            # The surprise: a secondary category the creator never declared.
            affinity[category] = round(rng.uniform(0.08, 0.62), 3)

    # Revealed price tolerance drifts from the stated band in either direction.
    drift = rng.uniform(-STATED_VS_REVEALED_DRIFT, STATED_VS_REVEALED_DRIFT)
    ceiling = int(creator.price_max * (1 + drift))
    floor = int(creator.price_min * (1 - abs(drift) * 0.5))

    # Sensitivities start from the stated intent scores, then drift.
    def sens(stated: int) -> float:
        return round(min(1.0, max(0.05, stated / 100 + rng.uniform(-0.22, 0.22))), 3)

    return LatentProfile(
        category_affinity=affinity,
        price_ceiling=max(creator.price_min + 50, ceiling),
        price_floor=max(0, floor),
        trend_sensitivity=sens(creator.intent_trend),
        commerce_sensitivity=sens(creator.intent_commerce),
        quality_sensitivity=sens(creator.intent_brand),
        novelty_preference=round(rng.uniform(0.25, 0.85), 3),
        seed=rng.randint(0, 10**6),
    )


# --------------------------------------------------------------------------
# the latent utility function — the ground truth
# --------------------------------------------------------------------------
def latent_utility(latent: LatentProfile, product: Product) -> tuple[float, dict[str, float]]:
    """How much this creator *really* wants to promote this product **now** (0-1).

    Returns the utility and the per-term scores, so the simulator can attribute
    a rejection to whichever term dragged it down.

    "Now" is load-bearing. A product the creator has already promoted has no
    remaining value to them, however good it is — you cannot post the same
    first-look twice. Treating its utility as still-high would score the engine
    down for correctly moving on, and the headline metric would fall while the
    engine behaved perfectly. Both the simulator and the evaluator read utility
    from this one function, so they cannot disagree about what is available.
    """
    if product.product_id in latent.promoted:
        return 0.0, {"already_promoted": 0.0}

    terms: dict[str, float] = {}

    terms["category"] = latent.category_affinity.get(product.category, 0.2)

    if latent.price_floor <= product.price <= latent.price_ceiling:
        terms["price"] = 1.0
    elif product.price > latent.price_ceiling:
        over = (product.price - latent.price_ceiling) / max(latent.price_ceiling, 1)
        terms["price"] = max(0.0, 1.0 - 1.5 * over)
    else:
        under = (latent.price_floor - product.price) / max(latent.price_floor, 1)
        terms["price"] = max(0.25, 1.0 - 0.6 * under)

    terms["trend"] = product.trend_score * latent.trend_sensitivity + (
        1 - latent.trend_sensitivity
    ) * 0.5
    terms["quality"] = min(1.0, max(0.0, (product.rating - 3.0) / 1.5)) * (
        latent.quality_sensitivity
    ) + (1 - latent.quality_sensitivity) * 0.5
    terms["commerce"] = min(1.0, product.conversion_rate / 0.055) * (
        latent.commerce_sensitivity
    ) + (1 - latent.commerce_sensitivity) * 0.5
    terms["novelty"] = 1.0 - product.creator_saturation * latent.novelty_preference

    # Category and price are gates; the rest average. A creator will not promote
    # off-niche or unaffordable product however good it is otherwise.
    soft = (terms["trend"] + terms["quality"] + terms["commerce"] + terms["novelty"]) / 4
    utility = terms["category"] * terms["price"] * (0.45 + 0.55 * soft)
    return round(min(1.0, max(0.0, utility)), 4), terms


# Which latent term maps to which rejection reason the creator would give.
TERM_TO_REASON = {
    "category": "not_my_niche",
    "price": "too_expensive",
    "trend": "not_trending",
    "quality": "dont_trust_product",
    "commerce": "audience_wont_care",
    "novelty": "already_promoted",
}


def decide_action(
    latent: LatentProfile, product: Product, rng: random.Random
) -> tuple[str, str | None, float]:
    """Return (action, reason, utility) for one shown product."""
    utility, terms = latent_utility(latent, product)

    if product.product_id in latent.promoted:
        return "skip", "already_promoted", 0.0

    # A little noise so the simulation is not a deterministic oracle; real
    # creators are inconsistent and the engine must cope with that.
    noisy = utility + rng.gauss(0, 0.06)

    if noisy >= latent.promote_threshold:
        return "promote", None, utility
    if noisy >= latent.save_threshold:
        return "save", None, utility

    # Attribute the rejection to the weakest term, which is what a creator
    # would actually say when asked why.
    weakest = min(terms, key=lambda k: terms[k])
    reason = TERM_TO_REASON[weakest]
    if reason == "already_promoted" and product.product_id not in latent.promoted:
        reason = "not_trending"      # saturation reads as "everyone has done it"
    return "skip", reason, utility


# --------------------------------------------------------------------------
# running rounds
# --------------------------------------------------------------------------
@dataclass
class RoundResult:
    round_number: int
    served: list[dict]
    promotes: int
    saves: int
    skips: int
    mean_served_utility: float
    nmv: int


def _persist_latent(db: Session, creator_id: str, latent: LatentProfile) -> None:
    row = db.get(SimulatedProfile, creator_id)
    if row is None:
        row = SimulatedProfile(creator_id=creator_id, latent=latent.to_json())
        db.add(row)
    else:
        row.latent = latent.to_json()
        row.updated_at = dt.datetime.now(dt.timezone.utc)
    db.commit()


def load_latent(db: Session, creator_id: str) -> LatentProfile | None:
    row = db.get(SimulatedProfile, creator_id)
    return LatentProfile.from_json(row.latent) if row else None


def ensure_latent(db: Session, creator: Creator, seed: int | None = None) -> LatentProfile:
    existing = load_latent(db, creator.creator_id)
    if existing is not None:
        return existing
    latent = build_latent(creator, seed)
    _persist_latent(db, creator.creator_id, latent)
    return latent


def run_round(
    db: Session,
    creator: Creator,
    latent: LatentProfile,
    round_number: int,
    top_k: int = 5,
) -> RoundResult:
    """One cycle: serve a slate, react to it, write the reactions back."""
    rng = random.Random(latent.seed + round_number)
    result = recommend(db, creator, category="bpc", top_k=top_k)

    served: list[dict] = []
    counts = {"promote": 0, "save": 0, "skip": 0}
    total_nmv = 0
    utilities: list[float] = []

    for rec in result.recommendations:
        product = rec.product
        action, reason, utility = decide_action(latent, product, rng)
        counts[action] += 1
        utilities.append(utility)

        db.add(
            FeedbackEvent(
                creator_id=creator.creator_id,
                product_id=product.product_id,
                action=action,
                reason=reason,
                served_score=rec.fit_score,
                model_version=result.model_version,
            )
        )

        interaction = get_or_create_interaction(db, creator.creator_id, product.product_id)

        if action == "promote":
            latent.promoted.add(product.product_id)
            interaction.promotes += 1
            # Orders follow from reach x utility x the product's own conversion.
            reach = creator.followers * creator.engagement_rate
            orders = int(reach * product.conversion_rate * utility * rng.uniform(0.4, 1.3))
            interaction.orders += orders
            nmv = orders * product.price
            interaction.nmv += nmv
            total_nmv += nmv
        elif action == "save":
            interaction.saves += 1
        # A click happens whenever the creator engaged enough to judge it.
        interaction.clicks += 1

        served.append(
            {
                "rank": rec.rank,
                "product_id": product.product_id,
                "title": product.title,
                "category": product.category,
                "price": product.price,
                "fit_score": rec.fit_score,
                "action": action,
                "reason": reason,
                "latent_utility": utility,
            }
        )

    db.commit()
    _persist_latent(db, creator.creator_id, latent)

    return RoundResult(
        round_number=round_number,
        served=served,
        promotes=counts["promote"],
        saves=counts["save"],
        skips=counts["skip"],
        mean_served_utility=round(sum(utilities) / len(utilities), 4) if utilities else 0.0,
        nmv=total_nmv,
    )


# --------------------------------------------------------------------------
# generating whole creators
# --------------------------------------------------------------------------
FIRST_NAMES = (
    "Aditi", "Ritika", "Neha", "Sanya", "Meher", "Ira", "Kavya", "Tara", "Diya",
    "Ananya", "Pooja", "Isha", "Rhea", "Nisha", "Simran", "Zoya", "Myra", "Anvi",
)
LAST_NAMES = (
    "Sharma", "Verma", "Pillai", "Iyer", "Nair", "Reddy", "Kapoor", "Singh",
    "Joshi", "Mehta", "Bose", "Rao", "Chopra", "Dutta", "Menon", "Gill",
)
BIO_TEMPLATES = {
    "Skincare": ("skincare and affordable routines", "ingredient-first skincare", "acne-safe routines"),
    "Makeup": ("everyday makeup on a budget", "festive looks and dupes", "five-minute makeup"),
    "Haircare": ("haircare science and routines", "curly hair care", "scalp health and growth"),
    "Personal Care": ("body care and grooming basics", "fragrance and body care", "daily grooming"),
}
SUB_NICHES = {
    "Skincare": ["serum", "routine", "brightening", "acne", "sunscreen", "affordable"],
    "Makeup": ["lips", "eyes", "base", "tint", "everyday", "affordable"],
    "Haircare": ["serum", "oil", "frizz", "scalp", "routine"],
    "Personal Care": ["body", "fragrance", "grooming", "daily-use"],
}


def generate_creator_payload(seed: int | None = None) -> dict:
    """A plausible creator profile, as if someone had just filled the form."""
    rng = random.Random(seed)
    niche = rng.choice(CATEGORIES)
    followers = int(10 ** rng.uniform(3.4, 5.6))
    goal = rng.choices(["reach", "revenue", "brand"], weights=[0.35, 0.45, 0.20])[0]

    age_min = rng.choice([18, 18, 20, 22, 25])
    age_max = age_min + rng.choice([6, 8, 10, 12])
    tiers = rng.choice([["T1", "T2"], ["T2", "T3"], ["T1", "T2", "T3"], ["T1"]])

    floor = rng.choice([100, 150, 200, 250, 300])
    ceiling = floor + rng.choice([300, 400, 500, 700, 1000])

    return {
        "name": f"{rng.choice(FIRST_NAMES)} {rng.choice(LAST_NAMES)}",
        "followers": followers,
        "niche": niche,
        "goal": goal,
        "price_min": floor,
        "price_max": ceiling,
        "avoid_categories": (
            [rng.choice([c for c in CATEGORIES if c != niche])] if rng.random() < 0.25 else []
        ),
        "audience_age_min": age_min,
        "audience_age_max": age_max,
        "audience_tiers": tiers,
        "sub_niches": rng.sample(SUB_NICHES[niche], k=min(4, len(SUB_NICHES[niche]))),
        "bio": rng.choice(BIO_TEMPLATES[niche]),
        "engagement_rate": round(
            # Smaller accounts engage harder — the usual inverse relationship.
            max(0.012, min(0.11, 0.14 - 0.018 * math.log10(max(followers, 10)) + rng.gauss(0, 0.01))),
            4,
        ),
    }
